#!/usr/bin/env python3
"""Regenerate docs/coverage.md, and the README entry-count badge JSON, from
the **Source tier:** field on every docs/**/*.md page.

Run this after adding, removing, or re-sourcing an entry, instead of
hand-editing docs/coverage.md or the badge count — both are derived, not
authored, so they can't drift out of sync with what the doc pages actually
say.
"""
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"
OUTPUT = DOCS / "coverage.md"
BADGE_OUTPUT = REPO_ROOT / "badges" / "entries.json"

CATEGORY_ORDER = [
    ("apex-accreditation", "Apex & Accreditation Infrastructure"),
    ("bis-core", "Cross-Sector Statutory — BIS Core"),
    ("food-agriculture", "Food & Agriculture"),
    ("health-pharma", "Health, Pharma & AYUSH"),
    ("energy-safety-environment", "Energy, Safety & Environment"),
    ("telecom-electronics", "Telecom & Electronics"),
    ("textiles", "Textiles & Handicrafts"),
    ("ip-trademarks", "Origin & Trademarks"),
    ("legal-metrology", "Legal Metrology"),
    ("private-voluntary", "Private / Industry Voluntary Marks"),
]

STATUTORY_LABEL = "Statutory / regulatory text"
OFFICIAL_LABEL = "Official scheme/administrative page"


def parse_doc(path: Path):
    text = path.read_text(encoding="utf-8")
    title = re.search(r"^# (.+)$", text, re.M).group(1)
    tier_line = re.search(r"\*\*Source tier:\*\*\s*(.+)", text)
    if not tier_line:
        raise SystemExit(f"{path}: missing **Source tier:** field")
    tier_text = tier_line.group(1)
    tier = STATUTORY_LABEL if tier_text.startswith(STATUTORY_LABEL) else OFFICIAL_LABEL
    m = re.search(r"## Primary source\n(.*?)\n##", text, re.S)
    first_bullet = m.group(1).strip().split("\n")[0] if m else ""
    link_text = re.search(r"\[([^\]]+)\]", first_bullet)
    citation = link_text.group(1) if link_text else "(none)"
    n_sources = len(re.findall(r"`sources/[^`]+\.\w+`", m.group(1) if m else ""))
    return {
        "title": title,
        "tier": tier,
        "citation": citation,
        "n_sources": n_sources,
        # relative to DOCS (where coverage.md lives), e.g. "bis-core/bis-isi-mark.md"
        "doc_link": path.relative_to(DOCS).as_posix(),
    }


def main():
    by_category = {key: [] for key, _ in CATEGORY_ORDER}
    for cat_key, _ in CATEGORY_ORDER:
        cat_dir = DOCS / cat_key
        if not cat_dir.is_dir():
            continue
        for md in sorted(cat_dir.glob("*.md")):
            by_category[cat_key].append(parse_doc(md))

    total = sum(len(v) for v in by_category.values())
    statutory = sum(1 for v in by_category.values() for e in v if e["tier"] == STATUTORY_LABEL)
    official = total - statutory

    lines = []
    lines.append("# Source coverage")
    lines.append("")
    lines.append("*Generated by `scripts/generate_coverage.py` from the **Source tier:** field "
                  "on every doc page — don't hand-edit this file, edit the doc pages and re-run "
                  "the script instead.*")
    lines.append("")
    lines.append(f"**{total} entries. {statutory} have the actual statutory or regulatory text "
                  f"mirrored (an Act, Rules, Regulations, Order or gazette notification). "
                  f"{official} are administrative/scheme pages — which is correct, not a gap, for "
                  f"an entry with no dedicated founding Act (an accreditation board, a voluntary "
                  f"industry mark, a scheme that runs on a guideline rather than a statute). "
                  f"Zero entries have no primary source mirrored at all.**")
    lines.append("")
    lines.append("Two tiers, not one \"covered/not covered\" flag, because the right primary "
                  "source for a body like NABCB (a QCI board with no founding Act of its own) is "
                  "genuinely its own \"About\" page — treating that as a gap and forcing a search "
                  "for a nonexistent statute would be a worse table, not a more complete one. See "
                  "[`docs/00-overview.md`](00-overview.md) for how the two tiers map onto the "
                  "four-layer regulatory model.")
    lines.append("")

    for cat_key, cat_label in CATEGORY_ORDER:
        entries = by_category[cat_key]
        if not entries:
            continue
        lines.append(f"## {cat_label}")
        lines.append("")
        lines.append("| Entry | Tier | Primary citation | Mirrored files |")
        lines.append("|---|---|---|---|")
        for e in entries:
            tier_short = "Statutory text" if e["tier"] == STATUTORY_LABEL else "Official page"
            lines.append(
                f"| [{e['title']}]({e['doc_link']}) | {tier_short} | "
                f"{e['citation']} | {e['n_sources']} |"
            )
        lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")

    # shields.io endpoint badge schema: https://shields.io/badges/endpoint-badge
    BADGE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    badge = {
        "schemaVersion": 1,
        "label": "entries",
        "message": f"{total} bodies & schemes",
        "color": "blue",
    }
    BADGE_OUTPUT.write_text(json.dumps(badge, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}: {total} entries "
          f"({statutory} statutory text, {official} official page).")
    print(f"Wrote {BADGE_OUTPUT.relative_to(REPO_ROOT)}: message={badge['message']!r}")


if __name__ == "__main__":
    sys.exit(main())
